@startuml
title Arkkitehtuuri

node "WebApp" {
  [Web App]
  [API Gateway]
}

node "TodoService" {
  [Todo Service]
  database "Postgres" {
    [Todo Storage]
  }
}

node "AuthService" {
  [Auth Service]
  database {
    [Users]
  }
}

[Web App] <--> [API Gateway] : HTTP
[API Gateway] -right-> [Auth Service] : Auth
[Auth Service] -left-> [API Gateway] : JWT
[Web App] .. [Auth Service]
[API Gateway] <--> [Todo Service] : REST
[Todo Service] - [Todo Storage]
[Auth Service] - [Users]

@enduml
